version: '3'

services:
  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - NAME=${NAME}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}