version: '3'

services:
  djangoapp:
    container_name: djangoapp
    image: ujstor/django_todolist
    ports:
      - "8050:8050"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
  
volumes:
  postgres-db: {}